version: '3'

services:
  django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # Persist database file
    environment:
      - DEBUG=True
